"""Reflow trainer (Contribution C).

Re-uses `flow_matching_loss.py` unchanged. The only structural change vs.
`train_adaptor_fm.py` is the batch source: `(Z_0, Z_1, cond)` are read from
disk (pre-generated by `generate_reflow_pairs.py`) instead of sampling
`Z_0 ∼ N(0, I)` and `Z_1` from the video dataloader. `compute_x_t` /
`compute_target_velocity` do not care where `Z_0`, `Z_1` come from, so the
loss is identical — `test_reflow_loss_matches_cfm_at_round0` pins this.

Reference: `README_contrib_BC.md` Section C.3.
"""

from __future__ import annotations

import argparse
import glob
import os
from pathlib import Path
from typing import Callable, Iterator, Optional, Tuple

import torch
from torch.utils.data import Dataset

from flow_matching_loss import (
    FlowMatchingConfig,
    cfm_ot_loss,
    compute_target_velocity,
    compute_x_t,
    sample_t,
)


class ReflowPairDataset(Dataset):
    """Reads `(Z_0, Z_1, cond)` tuples from `.pt` shards written by
    `generate_reflow_pairs.save_shards`."""

    def __init__(self, pairs_dir: str):
        self.shards = sorted(glob.glob(os.path.join(pairs_dir, "pairs-*.pt")))
        if not self.shards:
            raise FileNotFoundError(f"No pairs-*.pt shards under {pairs_dir!r}")
        self._index: list[Tuple[int, int]] = []
        self._cache: dict[int, dict] = {}
        for si, path in enumerate(self.shards):
            n = torch.load(path, map_location="cpu", weights_only=True)["z0"].shape[0]
            self._index.extend((si, j) for j in range(n))

    def __len__(self) -> int:
        return len(self._index)

    def _shard(self, si: int) -> dict:
        if si not in self._cache:
            self._cache[si] = torch.load(self.shards[si], map_location="cpu", weights_only=True)
        return self._cache[si]

    def __getitem__(self, i: int):
        si, j = self._index[i]
        s = self._shard(si)
        return s["z0"][j], s["z1"][j], s["cond"][j]


def reflow_training_step(
    velocity_model: Callable[[torch.Tensor, torch.Tensor, torch.Tensor], torch.Tensor],
    z0: torch.Tensor,
    z1: torch.Tensor,
    cond: torch.Tensor,
    t: torch.Tensor,
    config: FlowMatchingConfig,
) -> torch.Tensor:
    """One reflow loss evaluation. `velocity_model(x_t, t_idx, cond) -> v`.

    The loss is `mean((v - (z1 - (1-sigma)*z0))**2)`, i.e. exactly the CFM-OT
    loss with the disk-supplied coupling substituted for `(N(0,I), data)`.
    """
    x_t = compute_x_t(z0, z1, t, sigma_min=config.sigma_min)
    t_idx = (t * (config.num_train_timesteps - 1)).round().long()
    v = velocity_model(x_t, t_idx, cond)
    return cfm_ot_loss(v, z0, z1, sigma_min=config.sigma_min)


def assert_reflow_config(loss_type: Optional[str]) -> None:
    if str(loss_type).lower() != "cfm_ot":
        raise ValueError(
            f"Reflow requires loss_type='cfm_ot' (velocity prediction); got "
            f"'{loss_type}'. Reflow on an epsilon-prediction head is undefined."
        )


def train(
    velocity_model: torch.nn.Module,
    loader: Iterator[Tuple[torch.Tensor, torch.Tensor, torch.Tensor]],
    *,
    num_steps: int,
    lr: float = 1e-4,
    config: Optional[FlowMatchingConfig] = None,
    model_call: Optional[Callable] = None,
) -> list[float]:
    """Generic reflow training loop, reusable by the CLI and the toy tests.

    `model_call(model, x_t, t_idx, cond) -> v` adapts the loop to whatever the
    model's forward signature is (the demo stub, a real U-Net, a toy MLP)."""
    cfg = config or FlowMatchingConfig()
    if model_call is None:
        def model_call(m, x_t, t_idx, cond):
            return m(x_t, t_idx, cond)
    opt = torch.optim.Adam(velocity_model.parameters(), lr=lr)
    losses: list[float] = []
    for _ in range(num_steps):
        z0, z1, cond = next(loader)
        t = sample_t(z0.shape[0], z0.device, eps=cfg.t_eps)

        def vm(x_t, t_idx, c=cond):
            return model_call(velocity_model, x_t, t_idx, c)

        loss = reflow_training_step(vm, z0, z1, cond, t, cfg)
        opt.zero_grad(); loss.backward(); opt.step()
        losses.append(loss.item())
    return losses


def _cycle(dataset: ReflowPairDataset, batch_size: int) -> Iterator:
    from torch.utils.data import DataLoader
    dl = DataLoader(dataset, batch_size=batch_size, shuffle=True, drop_last=True)
    while True:
        for batch in dl:
            yield batch


def load_motioneditor_velocity_model(init_checkpoint: str):
    """Real path: init the MotionEditor CFM-OT U-Net from the Contribution A
    checkpoint and adapt its forward to `(x_t, t_idx, cond) -> v`. Imports are
    deferred so the module runs without the MotionEditor environment.

    Returns `(model, model_call)` where `model_call(model, x_t, t_idx, cond)`
    feeds the U-Net its skeleton conditioning the same way inference does."""
    try:
        from motion_editor.models.unet_2d_condition import UNet2DConditionModel
    except Exception as exc:  # pragma: no cover - environment-dependent
        raise SystemExit(
            "Real reflow training needs the MotionEditor package importable "
            f"(motion_editor.models...). Import failed: {exc}\n"
            "Run from the MotionEditor repo env (GPU), or use --stub for a CPU "
            "dev pass on the same pair shards."
        )
    model = UNet2DConditionModel.from_pretrained(init_checkpoint)

    def model_call(m, x_t, t_idx, cond):
        out = m(x_t, t_idx, encoder_hidden_states=None, controlnet_cond=cond)
        return out.sample if hasattr(out, "sample") else out

    return model, model_call


def main():
    ap = argparse.ArgumentParser(description="Reflow trainer (Contribution C).")
    ap.add_argument("--config", type=str, default=None)
    ap.add_argument("--reflow-pairs-dir", type=str, required=True)
    ap.add_argument("--reflow-round", type=int, default=1)
    ap.add_argument("--init-checkpoint", type=str, default=None,
                    help="Contribution A CFM-OT U-Net checkpoint (real mode).")
    ap.add_argument("--loss-type", type=str, default="cfm_ot")
    ap.add_argument("--num-steps", type=int, default=300)
    ap.add_argument("--batch-size", type=int, default=2)
    ap.add_argument("--lr", type=float, default=1e-4)
    ap.add_argument("--out", type=str, default="runs/reflow")
    ap.add_argument("--stub", action="store_true",
                    help="Train a tiny CPU stub model (no real U-Net checkpoint).")
    args = ap.parse_args()

    assert_reflow_config(args.loss_type)
    cfg = FlowMatchingConfig()
    ds = ReflowPairDataset(args.reflow_pairs_dir)
    loader = _cycle(ds, args.batch_size)

    if args.stub:
        z0, _, cond = ds[0]
        latent_ch = z0.shape[0]
        cond_dim = cond.numel()

        class StubVelocity(torch.nn.Module):
            def __init__(self):
                super().__init__()
                self.proj = torch.nn.Linear(cond_dim, latent_ch)
                self.scale = torch.nn.Parameter(torch.tensor(0.5))

            def forward(self, x_t, t_idx, cond):
                b = self.proj(cond.flatten(1).float()).view(cond.shape[0], -1,
                                                            *([1] * (x_t.dim() - 2)))
                return self.scale * x_t + 0.1 * b

        model, model_call = StubVelocity(), None
    elif args.init_checkpoint is not None:
        model, model_call = load_motioneditor_velocity_model(args.init_checkpoint)
    else:
        raise SystemExit(
            "Real reflow training needs --init-checkpoint (the Contribution A "
            "CFM-OT U-Net). Run with --stub for a CPU dev pass."
        )

    losses = train(model, loader, num_steps=args.num_steps, lr=args.lr,
                   config=cfg, model_call=model_call)

    out = Path(args.out) / f"checkpoint-reflow-{args.reflow_round}"
    out.mkdir(parents=True, exist_ok=True)
    torch.save(model.state_dict(), out / "model.pt")
    print(f"Reflow round {args.reflow_round}: final loss {losses[-1]:.4f}. "
          f"Saved to {out}/ (Contribution A checkpoint left untouched).")


__all__ = [
    "ReflowPairDataset",
    "reflow_training_step",
    "assert_reflow_config",
    "train",
]


if __name__ == "__main__":
    main()
